import streamlit as st
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image, ImageOps
from fpdf import FPDF
import base64
import time
import random
import os
import urllib.request

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="PneuSight Radiology", page_icon="🩻", layout="wide")

# --- CSS STYLING ---
st.markdown("""
    <style>
    /* Main Background */
    .stApp { background-color: #ffffff; }
    
    /* Professional Buttons */
    .stButton>button { 
        background-color: #004d99; 
        color: white; 
        border-radius: 5px; 
        height: 50px; 
        font-weight: bold; 
        border: none; 
    }
    .stButton>button:hover { background-color: #003366; color: white; }
    
    /* Upload Area */
    .css-1cpxqw2 { border: 2px dashed #004d99; background-color: #f0f7ff; }
    
    /* Fonts and Colors */
    h1, h2, h3 { color: #004d99; font-family: 'Segoe UI', sans-serif; }
    
    /* Status Boxes */
    .danger-box { background-color: #fff5f5; border-left: 6px solid #c53030; padding: 20px; color: #c53030; }
    .safe-box { background-color: #f0fff4; border-left: 6px solid #2f855a; padding: 20px; color: #2f855a; }
    </style>
    """, unsafe_allow_html=True)

# --- PDF REPORT GENERATOR ---
class MedicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.set_text_color(0, 77, 153) # Navy Blue
        self.cell(0, 10, 'PNEUSIGHT DIAGNOSTICS', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Powered by Aircpk.com AI Division', 0, 1, 'C')
        self.ln(20)
        self.set_draw_color(0, 77, 153)
        self.set_line_width(1)
        self.line(10, 35, 200, 35)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by PneuSight AI', 0, 0, 'C')

def create_pdf(img_path, status, confidence, filename):
    pdf = MedicalReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Patient Details
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f'Scan Reference: {filename}', 0, 1)
    pdf.cell(0, 8, f'Date: {time.strftime("%d %B %Y")}', 0, 1)
    pdf.cell(0, 8, f'Patient Reference: #{random.randint(100000, 999999)}', 0, 1)
    pdf.ln(5)
    
    # Image Section
    img = Image.open(img_path).convert('RGB')
    img.save("temp_scan.jpg")
    pdf.image("temp_scan.jpg", x=60, w=90)
    pdf.ln(10)
    
    # Diagnosis Box
    pdf.set_fill_color(245, 247, 250)
    pdf.rect(10, 150, 190, 35, 'F')
    pdf.set_y(155)
    
    pdf.set_font('Arial', 'B', 16)
    if "PNEUMONIA" in status:
        pdf.set_text_color(197, 48, 48) # Red
    else:
        pdf.set_text_color(47, 133, 90) # Green
        
    pdf.cell(0, 10, f"FINDING: {status}", 0, 1, 'C')
    
    pdf.set_text_color(50, 50, 50)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"AI Confidence Score: {confidence:.2f}%", 0, 1, 'C')
    
    # Disclaimer
    pdf.set_y(240)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by PneuSight AI. It is intended for preliminary screening only. NOT a definitive medical diagnosis. Verify with a radiologist.")
    
    return pdf.output(dest="S").encode("latin-1")

# --- MODEL DOWNLOADER (GitHub Release Fix) ---
def download_model():
    model_path = 'best_xray_model.keras'
    
    # ⚠️ IMPORTANT: REPLACE THIS URL WITH YOUR GITHUB RELEASE LINK
    url = "PASTE_YOUR_LINK_HERE" 
    
    # Check if we already have the model
    if not os.path.exists(model_path):
        with st.spinner("Downloading AI Brain (This happens only once)..."):
            try:
                urllib.request.urlretrieve(url, model_path)
                st.success("Model Downloaded Successfully!")
            except Exception as e:
                st.error(f"Failed to download model: {e}")
                st.stop()
    return model_path

# --- LOAD MODEL ---
@st.cache_resource
def load_my_model():
    # 1. Download file if missing
    path = download_model()
    # 2. Load Keras model
    return load_model(path)

try:
    model = load_my_model()
except:
    st.error("⚠️ Model initialization failed. Please check the download link in app.py")
    st.stop()

# --- ROBUST PREDICTION (TTA) ---
def make_robust_prediction(img):
    """
    Predicts 3 times (Normal, Mirror, Zoom) and takes the average.
    """
    img = img.convert('RGB')
    images_to_test = []
    
    # 1. Standard Image
    images_to_test.append(img)
    
    # 2. Mirrored Image
    images_to_test.append(ImageOps.mirror(img))
    
    # 3. Zoomed Crop
    w, h = img.size
    zoom = img.crop((w*0.1, h*0.1, w*0.9, h*0.9)).resize((w, h))
    images_to_test.append(zoom)
    
    # Prepare Batch
    batch = []
    for i in images_to_test:
        i_resized = i.resize((224, 224))
        i_array = image.img_to_array(i_resized) / 255.0
        batch.append(i_array)
    
    # Predict and Average
    predictions = model.predict(np.array(batch))
    return np.mean(predictions)

# --- MAIN UI ---
st.title("🏥 PneuSight Radiology")
st.markdown("### Advanced AI Screening Portal")

uploaded_files = st.file_uploader("Upload Patient X-Rays (DICOM/JPEG)", type=["jpg", "jpeg", "png"], accept_multiple_files=True)

if uploaded_files and st.button("RUN PNEUSIGHT PROTOCOL"):
    st.divider()
    progress_bar = st.progress(0)
    
    for idx, uploaded_file in enumerate(uploaded_files):
        col1, col2 = st.columns([1, 1.5])
        
        # Open Image
        img = Image.open(uploaded_file)
        
        # Get Score using TTA
        score = make_robust_prediction(img)
        
        # Determine Status
        if score > 0.5:
            status = "PNEUMONIA DETECTED"
            confidence = score * 100
            box_class = "danger-box"
            icon = "⚠️"
        else:
            status = "NORMAL / CLEAR"
            confidence = (1 - score) * 100
            box_class = "safe-box"
            icon = "✅"
            
        # Display Results
        with col1:
            st.image(img, caption=f"Scan: {uploaded_file.name}", width=250)
            
        with col2:
            st.markdown(f"""
            <div class="{box_class}">
                <h3>{icon} {status}</h3>
                <p><strong>Confidence:</strong> {confidence:.2f}%</p>
                <p style="font-size:0.9em; color:grey;">(Verified via Multi-View TTA)</p>
            </div>
            """, unsafe_allow_html=True)
            
            # Generate and Offer PDF
            pdf_data = create_pdf(uploaded_file, status, confidence, uploaded_file.name)
            b64 = base64.b64encode(pdf_data).decode()
            href = f'<a href="data:application/octet-stream;base64,{b64}" download="PneuSight_Report_{uploaded_file.name}.pdf" style="text-decoration:none;"><button style="background-color:#004d99;color:white;width:100%;padding:10px;border:none;border-radius:5px;cursor:pointer;">📄 Download Report</button></a>'
            st.markdown(href, unsafe_allow_html=True)
            
        st.divider()
        progress_bar.progress((idx + 1) / len(uploaded_files))